{
 "title": "Solr",
 "description": "Solr Dashboard Azure Dev Subscription 00002",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "zk_host",
    "query": "label_values(solr_ping{zk_host=~\".+\"},zk_host)"
   },
   {
    "name": "collection",
    "query": "label_values(solr_ping{zk_host=\"$zk_host\",collection=~\".+\"},collection)"
   },
   {
    "name": "shard",
    "query": "label_values(solr_collections_shard_state{zk_host=\"$zk_host\",collection=\"$collection\",shard=~\".+\"},shard)"
   },
   {
    "name": "replica",
    "query": "label_values(solr_collections_replica_state{zk_host=\"$zk_host\",collection=\"$collection\",shard=\"$shard\",replica=\".+\"},replica)"
   },
   {
    "name": "base_url",
    "query": "label_values(solr_ping{base_url=~\".+\"},base_url)"
   },
   {
    "name": "core",
    "query": "label_values(solr_ping{base_url=~\"$base_url\"},core)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Cores",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(solr_metrics_core_searcher_documents)"
    }
   ]
  },
  {
   "title": "Total cores size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(solr_metrics_core_index_size_bytes{base_url=~\"$base_url\"})"
    }
   ]
  },
  {
   "title": "Total documents",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(solr_metrics_core_searcher_documents)"
    }
   ]
  },
  {
   "title": "Document Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(solr_metrics_core_index_size_bytes{base_url=~\"$base_url\"}) / sum(solr_metrics_core_searcher_documents{base_url=~\"$base_url\"})"
    }
   ]
  },
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Total Shared Status (Active vs. InActive)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(solr_collections_shard_state == 1)",
     "legendFormat": "Total Shared Active"
    },
    {
     "expr": "sum(solr_collections_shard_state == 0)",
     "legendFormat": "Total Shared InActive"
    }
   ]
  },
  {
   "title": "Solr Nodes - % CPU Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 6, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_os_cpu_load{base_url=~\"$base_url\", item=\"systemCpuLoad\"}",
     "legendFormat": "{{base_url}} "
    }
   ]
  },
  {
   "title": "Solr docs rate (docs per sec)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(solr_metrics_core_searcher_documents[5m]))",
     "legendFormat": " Solr Index Rate (docs per sec)"
    }
   ]
  },
  {
   "title": "Total Documents Per Day",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (day) ( label_replace(solr_metrics_core_searcher_documents{core=~\"$core\", item=\"numDocs\", category=\"SEARCHER\"}, \"day\", \"$month-$day\", \"core\", \"((Events_000000000000_)(?P<year>[[:alnum:]]{2})(?P<month>[[:alnum:]]{2})(?P<day>[[:alnum:]]{2}))(.*)\"))",
     "legendFormat": "{{day}}"
    }
   ]
  },
  {
   "title": "Total Collections count per day (in case single shared)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (day) ( label_replace(solr_metrics_core_searcher_documents{core=~\"$core\", item=\"numDocs\", category=\"SEARCHER\"}, \"day\", \"$month-$day\", \"collection\", \"((Events_000000000000_)(?P<year>[[:alnum:]]{2})(?P<month>[[:alnum:]]{2})(?P<day>[[:alnum:]]{2}))(.*)\"))",
     "legendFormat": "{{day}}"
    }
   ]
  },
  {
   "title": "Update Requests distribution (per node)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(label_replace(increase(solr_metrics_core_update_requests_total{base_url=~\"$base_url\"}[20m]) > 10, \"coreTimeSolt\", \"$1\", \"core\", \"Events_0_([0-9]{1,10}).*_[0-9].*_n1\")) by (base_url)",
     "legendFormat": "{{base_url}}"
    }
   ]
  },
  {
   "title": "Total Soft commits (per node)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(solr_metrics_core_update_handler_soft_auto_commits_executed_number > 0) by (base_url)",
     "legendFormat": "{{base_url}}"
    }
   ]
  },
  {
   "title": "Total Hard commits (per node)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(solr_metrics_core_update_handler_auto_commits_total > 0) by (base_url)",
     "legendFormat": "{{base_url}}"
    }
   ]
  },
  {
   "title": "Documents per shared (top)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(800, solr_metrics_core_searcher_documents{item=\"numDocs\"})",
     "legendFormat": "{{collection}}"
    }
   ]
  },
  {
   "title": "Size per shared (top)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(800, solr_metrics_core_index_size_bytes{base_url=~\"$base_url\"})",
     "legendFormat": "{{collection}}"
    }
   ]
  },
  {
   "title": "Free Physical Memory Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_os_memory_bytes{base_url=~\"$base_url\",item=~\"freePhysicalMemorySize\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_memory_heap_bytes{base_url=~\"$base_url\",item=~\"used\"}",
     "legendFormat": "{{base_url}} {{item}}"
    },
    {
     "expr": "avg(solr_metrics_jvm_memory_heap_bytes{base_url=~\"$base_url\",item=~\"committed\"})",
     "legendFormat": " JVM committed"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_gc_total{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Request Time -  percentile 75th",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_node_requestTimes_p75_ms > 0",
     "legendFormat": "{{base_url}}{{handler}}"
    }
   ]
  },
  {
   "title": "Total Response Code Response (2xx OK ;  4xx\\5xx BAD)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jetty_response_total",
     "legendFormat": "{{base_url}} {{status}}"
    }
   ]
  },
  {
   "title": "Total Solr Node Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_node_errors_total{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}}{{handler}}"
    }
   ]
  },
  {
   "title": "Total Live Solr nodes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "solr_collections_live_nodes", "legendFormat": "Total live nodes" }
   ]
  },
  {
   "title": "Total Solr Cores - Ping Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum(solr_ping{base_url=~\"$base_url\",core!=\"\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(solr_metrics_jvm_os_file_descriptors{base_url=~\"$base_url\",item=~\"maxFileDescriptorCount\"})",
     "legendFormat": "maxFileDescriptorCount"
    },
    {
     "expr": "solr_metrics_jvm_os_file_descriptors{base_url=~\"$base_url\",item=~\"openFileDescriptorCount\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Overseer - Collection queue size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_overseer_collection_queue_size",
     "legendFormat": "Overseer queue size"
    }
   ]
  },
  {
   "title": "JVM Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_gc_total{base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "GC Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_gc_seconds_total{base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "Heap Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_memory_heap_bytes{base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "Non-Heap Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_memory_non_heap_bytes{base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "Pool Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_memory_pools_bytes{base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{space}} {{item}}"
      }
     ]
    },
    {
     "title": "Memory Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_memory_bytes{base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_threads{base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Jetty Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response Code Response (2xx OK ;  4xx\\5xx BAD)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jetty_response_total",
       "legendFormat": "{{base_url}} {{status}}"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jetty_requests_total",
       "legendFormat": "{{base_url}} {{method}}"
      }
     ]
    },
    {
     "title": "Dispatches",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jetty_dispatches_total",
       "legendFormat": "{{base_url}}"
      }
     ]
    }
   ]
  },
  {
   "title": "OS Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_os_memory_bytes{base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_os_file_descriptors{base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "% CPU Time - VM  Vs. Solr Process CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_os_cpu_load{base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Node Requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_node_requests_total",
       "legendFormat": "{{base_url}} ;   handler={{handler}}"
      }
     ]
    },
    {
     "title": "Request Time -  percentile 75th",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_node_requestTimes_p75_ms",
       "legendFormat": "{{base_url}}{{handler}}"
      }
     ]
    },
    {
     "title": "Client Errors - Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_node_client_errors_total{base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}}{{handler}}"
      }
     ]
    },
    {
     "title": "Server Errors - Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_node_server_errors_total{base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}}{{handler}}"
      }
     ]
    },
    {
     "title": "Total Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_node_errors_total{base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}}{{handler}}"
      }
     ]
    },
    {
     "title": "Timeouts",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_node_timeouts_total{base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}}{{handler}}"
      }
     ]
    },
    {
     "title": "Core Root File System",
     "type": "graph",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_node_core_root_fs_bytes{base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "Cores",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_node_cores{base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "Thread Pool Completed",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_node_thread_pool_completed_total",
       "legendFormat": "{{base_url}} {{handler}} {{executor}}"
      }
     ]
    },
    {
     "title": "Thread Pool Submitted",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_node_thread_pool_submitted_total",
       "legendFormat": "{{base_url}} {{handler}} {{executor}}"
      }
     ]
    },
    {
     "title": "Thread Pool Running",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_node_thread_pool_running{base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{handler}} {{executor}}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_node_connections{base_url=~\"$base_url\"}",
       "legendFormat": "{{base_url}} {{handler}} {{item}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Search Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "row - Initial Response Time",
     "type": "graph",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_varonis_search_event_initime_avg_row_response > 0",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "row - total response time",
     "type": "graph",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 20 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_varonis_search_event_totaltime_avg_rows_response > 0 and win_perfmon_varonis_search_event_totaltime_avg_rows_response < 8000000",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "facet - Initial Response Time",
     "type": "graph",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_varonis_search_event_initime_avg_facet_response > 0",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "facet - Total Response Time",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_varonis_search_event_totaltime_avg_facets_response > 0 and win_perfmon_varonis_search_event_totaltime_avg_facets_response < 18000000",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Solr Search - error Get Collection Details - Total",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "grok_solrSearchLog_errorGetCollectionDetails_total"
      }
     ]
    },
    {
     "title": "Solr Search - error Facet Run Query - Total",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "grok_solrSearchLog_errorFacetRunQuery_total"
      }
     ]
    },
    {
     "title": "Solr Search -  error Row Run Query - Total",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "grok_solrSearchLog_errorRowRunQuery_total"
      }
     ]
    },
    {
     "title": "Solr Search -  search Request - entity Event quantity - Total",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "grok_solrSearchLog_searchRequest_entityEvent_quantity_total"
      }
     ]
    },
    {
     "title": "Solr Search - Event - number of searches POST\\PUT",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_varonis_search_event_perfmon_idu_search_event_number_of_searches_postput"
      },
      {
       "expr": "win_perfmon_varonis_search_event_number_of_searches_postput"
      }
     ]
    },
    {
     "title": "Solr Search -  task entity Event - Average Runtime",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "grok_solrSearchLog_task_entityEvent_averageRuntimeInMS"
      }
     ]
    },
    {
     "title": "Solr Search - snapshot Cache - last Time Accessed From Creation (MIN)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "m" }
     ],
     "targets": [
      {
       "expr": "grok_solrSearchLog_snapshotCache_lastTimeAccessedFromCreation_inMinutes"
      }
     ]
    },
    {
     "title": "Solr Search - snapshot Cache - items In Cache",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "grok_solrSearchLog_snapshotCache_itemsInCache"
      }
     ]
    },
    {
     "title": "Solr Search - Event - Collections per search",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_varonis_search_event_perfmon_idu_search_event_collections_per_search"
      },
      {
       "expr": "win_perfmon_varonis_search_event_collections_per_search"
      }
     ]
    },
    {
     "title": "Solr Search - Event - concurrent tasks",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_varonis_search_event_perfmon_idu_search_event_concurrent_taks"
      },
      {
       "expr": "win_perfmon_varonis_search_event_concurrent_taks"
      }
     ]
    },
    {
     "title": "Solr Search - Event - facet tasks per search",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_varonis_search_event_perfmon_idu_search_event_facet_tasks_per_search"
      },
      {
       "expr": "win_perfmon_varonis_search_event_facet_tasks_per_search"
      }
     ]
    },
    {
     "title": "Solr Search - Event - Pending tasks search",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_varonis_search_event_perfmon_idu_search_event_pending_tasks_search"
      },
      {
       "expr": "win_perfmon_varonis_search_event_pending_tasks_search"
      }
     ]
    },
    {
     "title": "Solr Search - Event - Terminated POST\\PUT requests",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_varonis_search_event_perfmon_idu_search_event_terminated_postput_requests"
      },
      {
       "expr": "win_perfmon_varonis_search_event_terminated_postput_requests"
      }
     ]
    },
    {
     "title": "Solr Search - Event - Terminated POST search requests",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_varonis_search_event_perfmon_idu_search_event_terminated_post_search_requests"
      },
      {
       "expr": "win_perfmon_varonis_search_event_terminated_post_search_requests"
      }
     ]
    },
    {
     "title": "Solr Search - Event - Avg. removed terminated facet tasks",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_varonis_search_event_perfmon_idu_search_event_avg_removed_terminated_facet_tasks"
      },
      {
       "expr": "win_perfmon_varonis_search_event_avg_removed_terminated_facet_tasks"
      }
     ]
    },
    {
     "title": "Solr Search - Event - Avg. removed terminated facet tasks",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_varonis_search_event_perfmon_idu_search_event_avg_removed_terminated_facet_tasks"
      },
      {
       "expr": "win_perfmon_varonis_search_event_avg_removed_terminated_facet_tasks"
      }
     ]
    }
   ]
  },
  {
   "title": "Solr Services (Loader, SMS, Monitor)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "Loader Service - Documents Loaded to Solr - total",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_varonis_solr_loader_idu_documents_loaded_to_solr_total",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Loader Service - Documents Loaded to Solr - rate (docs per sec)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 71 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_varonis_solr_loader_idu_documents_loaded_to_solr_rate_docs_per_sec",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Loader Service - Files Failures - Total",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_varonis_solr_loader_idu_files_failures_total",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Loader Service - Event age in Minutes - Average",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 76 },
     "yaxes": [
      { "format": "m" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_varonis_solr_loader_idu_event_age_in_minutes_avaerage",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Solr Management - solr Node Connection Status - Total",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 81 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "grok_solrManagementLog_solrNode_noConnection_total"
      }
     ]
    },
    {
     "title": "Solr Management- error loading Config - Total",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 81 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "grok_solrManagementLog_errorLoadingConfig_total"
      }
     ]
    },
    {
     "title": "Solr Management - error get collection details - Total",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 81 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "grok_solrManagementLog_errorGetCollectionDetails_total"
      }
     ]
    },
    {
     "title": "Solr Monitor - Core size reached Threshold - Total",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 87 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "grok_solrMonitorLog_collectionCore_reachedThresholdIsTrue_total",
       "legendFormat": "collectionName={{collectionName}} \\ coreSizeInBytes={{coreSize}}"
      }
     ]
    },
    {
     "title": "Core/Index size (GB)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 93 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "topk(200,solr_metrics_core_index_size_bytes{base_url=~\"$base_url\"})",
       "legendFormat": "{{core}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IDU HW",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "IDU - % CPU Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_processor_idu_precent_processor_time",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "IDU - % CPU Time",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "win_perfmon_processor_idu_precent_processor_time"
      }
     ]
    },
    {
     "title": "IDU - Context switches per sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_system_idu_context_switches_sec",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "IDU - Processor queue length",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_system_idu_processor_queue_length",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "IDU - Available GBytes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_memory_idu_available_mbytes",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "IDU Disk % Free Space",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_disk_idu_precent_free_space_FPartition"
      }
     ]
    },
    {
     "title": "IDU Disk Latency (ms)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_disk_idu_avg_disk_sec_Write_FPartition",
       "legendFormat": "write - "
      },
      {
       "expr": "win_perfmon_disk_idu_avg_disk_sec_read_FPartition",
       "legendFormat": "read - "
      }
     ]
    },
    {
     "title": "IDU Partition (=DataLake) Bytes/sec = Throughput",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_disk_idu_disk_Bytes_sec_FPartition",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "IDU Partition (=DataLake) Transfers/sec = IOPS",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_disk_idu_disk_Transfers_sec_FPartition",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "IDU Network - Established connection",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_tcpv4_idu_connection_established"
      }
     ]
    },
    {
     "title": "IDU Network - Active connection",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_tcpv4_idu_connection_active"
      }
     ]
    },
    {
     "title": "IDU Network - Failures connection",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_tcpv4_idu_connection_failures"
      }
     ]
    }
   ]
  },
  {
   "title": "Solr HW",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "Solr Node 1 - % CPU Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_processor_solr1_precent_processor_time",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Solr Node 1 - % CPU Time",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 49 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "win_perfmon_processor_solr1_precent_processor_time"
      }
     ]
    },
    {
     "title": "Solr Nodes - % CPU Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_os_cpu_load{base_url=~\"$base_url\", item=\"systemCpuLoad\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "Solr Available MBytes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_memory_solr1_available_mbytes"
      }
     ]
    },
    {
     "title": "Solr Partition latency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_disk_solr1_avg_disk_sec_Write_FPartition",
       "legendFormat": "write - {{instance}}"
      },
      {
       "expr": "win_perfmon_disk_solr1_avg_disk_sec_read_FPartition",
       "legendFormat": "read - {{instance}}"
      }
     ]
    },
    {
     "title": "Solr Disk % Free Space",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 67 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_disk_solr1_precent_free_space_FPartition"
      }
     ]
    },
    {
     "title": "Solr Partition (=SolrData) Bytes/sec = Throughput",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_disk_solr1_disk_Bytes_sec_FPartition",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "IDU Partition (=DataLake) Transfers/sec = IOPS",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 73 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "win_perfmon_disk_idu_disk_Transfers_sec_FPartition",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "SolrData Throughput -  Bytes/sec",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 78 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(wmi_logical_disk_write_bytes_total{volume=\"E:\"}[5m])",
       "legendFormat": "{{volume}} partition - Write Throughput"
      },
      {
       "expr": "irate(wmi_logical_disk_read_bytes_total{volume=\"E:\"}[5m])",
       "legendFormat": "{{volume}} partition - ReadThroughput"
      }
     ]
    },
    {
     "title": "SolrData IOPS -  IOPS",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 78 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "irate(wmi_logical_disk_writes_total{volume=\"E:\"}[5m])",
       "legendFormat": "{{volume}} partition - Write IOPS"
      },
      {
       "expr": "irate(wmi_logical_disk_reads_total{volume=\"E:\"}[5m])",
       "legendFormat": "{{volume}} partition - Read IOPS"
      }
     ]
    },
    {
     "title": "Solr Free Memory",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 83 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "wmi_os_physical_memory_free_bytes"
      }
     ]
    },
    {
     "title": "SolrData - Disk Queue Length",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 83 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wmi_logical_disk_requests_queued{volume=\"E:\"}"
      }
     ]
    }
   ]
  }
 ]
}